# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

  
target 'project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', path: '../node_modules/react-native', :subspecs => [    
        'Core',
        'RCTActionSheet',
        'RCTAnimation',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
        'DevSupport'
    ]    

  pod 'react-native-maps', path: '../node_modules/react-native-maps/'


  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
 
  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  
   #pod 'GoogleMaps'
   #pod 'Google-Maps-iOS-Utils'
  
  pod 'GoogleSignIn'
  pod 'Firebase/Messaging'

  # pod 'Firebase/Core'
  # Pods for ste


 #  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

 # pod 'react-native-maps', :path => '../node_modules/react-native-maps'

end
